[default]
description = "Default permissions for the PowerSync plugin"
permissions = [
    "allow-open",
    "allow-close",
    "allow-execute",
    "allow-execute-batch",
    "allow-get-all",
    "allow-get-optional",
    "allow-begin-transaction",
    "allow-commit-transaction",
    "allow-rollback-transaction",
]
